kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: RoleBinding-example
  namespace: test
  # annotations:
  #   CCE.com/IAM: 'true'
roleRef:
  kind: Role
  name: role-example
  apiGroup: ""
subjects:
- kind: ServiceAccount
  name: build-robot
  apiGroup: ""
